export const generosLiterarios = [
  "Ação e aventura",
  "Alegoria",
  "Artigo acadêmico",
  "Auto",
  "Autoajuda",
  "Autobiografia",
  "Aventura",
  "Aventura clássica",
  "Biografia",
  "Cartas",
  "Chick-lit",
  "Ciência",
  "Científico",
  "Comédia",
  "Contemporâneo",
  "Conto",
  "Contos de fadas",
  "Correspondências",
  "Crônica",
  "Cyberpunk",
  "Diário",
  "Didático",
  "Distopia",
  "Drama",
  "Drama social",
  "Elegia",
  "Ensaio",
  "Epopeia",
  "Espionagem",
  "Espiritualidade",
  "Existencialismo",
  "Fábula",
  "Fantasia",
  "Ficção científica",
  "Filosófico",
  "Haikai",
  "Hino",
  "Histórico",
  "Horror gótico",
  "Humor",
  "Infantil",
  "Juvenil",
  "Literatura fantástica juvenil",
  "Lírico",
  "Memórias",
  "Mistério",
  "Naturalismo",
  "Noir",
  "Novela",
  "Ode",
  "Parabólica",
  "Poesia",
  "Poesia moderna",
  "Policial",
  "Psicológico",
  "Realismo",
  "Religioso",
  "Reportagem literária",
  "Romance",
  "Romance contemporâneo",
  "Romance de época",
  "Romance erótico",
  "Romance histórico",
  "Romance juvenil",
  "Romance policial",
  "Romance psicológico",
  "Slam",
  "Slasher",
  "Sobrenatural",
  "Soneto",
  "Space opera",
  "Steampunk",
  "Suspense",
  "Técnico",
  "Terror",
  "Terror cósmico",
  "Tragédia",
  "Utopia",
  "Épico"
]